apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: mne.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3005
          - path: /api/cards/?(.*)
            pathType: Prefix
            backend:
              service:
                name: cards-srv
                port:
                  number: 3006
          - path: /api/repetition/?(.*)
            pathType: Prefix
            backend:
              service:
                name: repetition-srv
                port:
                  number: 3002
          - path: /api/repetition-history/?(.*)
            pathType: Prefix
            backend:
              service:
                name: repetition-history-srv
                port:
                  number: 3007
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: web-client-srv
                port:
                  number: 3000
