apiVersion: apps/v1
kind: Deployment
metadata:
  name: repetition-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repetition
  template:
    metadata:
      labels:
        app: repetition
    spec:
      containers:
        - name: repetition
          image: krodina/repetition:latest
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: mnemosyne
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: MONGO_URI
              value: "mongodb://repetition-mongo-srv:27017/repetition"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: repetition-srv
spec:
  selector:
    app: repetition
  ports:
    - name: repetition
      protocol: TCP
      port: 3002
      targetPort: 3002
