apiVersion: apps/v1
kind: Deployment
metadata:
  name: repetition-history-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repetition-history
  template:
    metadata:
      labels:
        app: repetition-history
    spec:
      containers:
        - name: repetition-history
          image: krodina/repetition-history:latest
          env:
            - name: MONGO_URI
              value: "mongodb://repetition-history-mongo-srv:27017/repetition-history"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: mnemosyne
            - name: NATS_URL
              value: "http://nats-srv:4222"

---
apiVersion: v1
kind: Service
metadata:
  name: repetition-history-srv
spec:
  selector:
    app: repetition-history
  ports:
    - name: repetition-history
      protocol: TCP
      port: 3008
      targetPort: 3008
