apiVersion: apps/v1
kind: Deployment
metadata:
  name: repetition-scheduler-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repetition-scheduler
  template:
    metadata:
      labels:
        app: repetition-scheduler
    spec:
      containers:
        - name: repetition-scheduler
          image: krodina/repetition-scheduler:latest
          env:
            - name: MONGO_URI
              value: "mongodb://repetition-scheduler-mongo-srv:27017/repetition-scheduler"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_CLUSTER_ID
              value: mnemosyne
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: repetition-scheduler-srv
spec:
  selector:
    app: repetition-scheduler
  ports:
    - name: repetition-scheduler
      protocol: TCP
      port: 3009
      targetPort: 3009
